# Generated by Django 5.2.17 on 2026-08-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('discover_expansions', 'Discover Expansions'), ('discover_cards', 'Discover Cards'), ('refresh_prices', 'Refresh Prices')], max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('backing_up', 'Backing Up'), ('running', 'Running'), ('cancel_requested', 'Cancel Requested'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, max_length=250)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=250)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.printing')),
                ('expansion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.expansion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scraping.scrapejob')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scrapejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='uniq_single_running_job'),
        ),
        migrations.AddConstraint(
            model_name='scrapejobitem',
            constraint=models.UniqueConstraint(condition=models.Q(('card__isnull', False)), fields=('job', 'card'), name='uniq_jobitem_card'),
        ),
        migrations.AddConstraint(
            model_name='scrapejobitem',
            constraint=models.UniqueConstraint(condition=models.Q(('expansion__isnull', False)), fields=('job', 'expansion'), name='uniq_jobitem_expansion'),
        ),
    ]
