# Generated by Django 5.2.17 on 2026-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrome_binary', models.CharField(blank=True, help_text='Full path to the Chrome executable. Leave blank to use the platform default from settings.', max_length=500)),
                ('challenge_timeout', models.PositiveIntegerField(default=180, help_text='Seconds to wait for a Cloudflare check to clear (you clicking the checkbox counts) before stopping the run.')),
                ('min_item_delay', models.PositiveIntegerField(default=4, help_text='Shortest pause between items, in seconds.')),
                ('max_item_delay', models.PositiveIntegerField(default=9, help_text='Longest pause between items. Slower is safer — bursts are what get an IP blocked.')),
            ],
            options={
                'verbose_name': 'scraper settings',
                'verbose_name_plural': 'scraper settings',
            },
        ),
    ]
