# Generated by Django 5.2.17 on 2026-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_scraper_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='job_type',
            field=models.CharField(choices=[('discover_expansions', 'Scrape: discover expansions'), ('discover_cards', 'Scrape: discover cards'), ('refresh_prices', 'Scrape: refresh prices'), ('import_catalog', 'API: import card catalog'), ('resolve_printings', 'API: match cards to catalog'), ('cache_art', 'API: download card art'), ('api_prices', 'API: fill missing prices')], max_length=25),
        ),
    ]
