# Generated by Django 5.2.17 on 2026-08-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_close_out_terminal_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersettings',
            name='challenge_attempts',
            field=models.PositiveIntegerField(default=4, help_text="How many times to back off and retry when a Cloudflare check doesn't clear, before giving up on the run. Each attempt waits longer and starts a fresh browser."),
        ),
    ]
