# Generated by Django 5.2.17 on 2026-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_challenge_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapersettings',
            name='max_item_delay',
            field=models.PositiveIntegerField(default=9, help_text='Longest pause between Cardmarket page loads. Slower is safer — bursts are what get an IP blocked.'),
        ),
        migrations.AlterField(
            model_name='scrapersettings',
            name='min_item_delay',
            field=models.PositiveIntegerField(default=4, help_text='Shortest pause between Cardmarket page loads, in seconds. Applies to the scraper jobs only.'),
        ),
    ]
