# Generated by Django 5.2.17 on 2026-08-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_trend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_30d_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('legacy_import', 'Legacy Import'), ('card_page', 'Card Page'), ('expansion_list', 'Expansion List')], max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='catalog.printing')),
                ('scrape_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.scrapejob')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['card', '-observed_at'], name='pricing_pri_card_id_5cf07a_idx')],
            },
        ),
    ]
