# Generated by Django 5.2.17 on 2026-08-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesnapshot',
            name='scrape_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraping.scrapejob'),
        ),
    ]
