# Generated by Django 5.2.17 on 2026-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricesnapshot_scrape_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesnapshot',
            name='source',
            field=models.CharField(choices=[('legacy_import', 'Legacy Import'), ('card_page', 'Card Page'), ('expansion_list', 'Expansion List'), ('catalog_api', 'Catalog Api')], max_length=20),
        ),
    ]
