# Generated by Django 5.2.17 on 2026-08-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('keeper_quantity', models.PositiveIntegerField(default=0, help_text='Copies reserved, never offered for sale (replaces cards-to-keep.json).')),
                ('condition', models.CharField(blank=True, choices=[('MT', 'Mint'), ('NM', 'Near Mint'), ('EX', 'Excellent'), ('GD', 'Good'), ('LP', 'Light Played'), ('PL', 'Played'), ('PO', 'Poor')], max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='catalog.printing')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('listed', 'Listed'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('import_legacy', 'Import Legacy'), ('manual_edit', 'Manual Edit'), ('bulk_edit', 'Bulk Edit'), ('sale', 'Sale'), ('trade', 'Trade'), ('correction', 'Correction'), ('undo', 'Undo')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_changes', to='catalog.printing')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='collection.holding')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sell_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collection.sellpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_at_listing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.printing')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collection.sellpackage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('owner', 'card'), name='uniq_holding_owner_card'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('keeper_quantity__lte', models.F('quantity'))), name='keeper_lte_quantity'),
        ),
        migrations.AddIndex(
            model_name='quantitychange',
            index=models.Index(fields=['card', 'created_at'], name='collection__card_id_d89054_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellpackageitem',
            constraint=models.UniqueConstraint(fields=('package', 'card'), name='uniq_package_card'),
        ),
    ]
