# Generated by Django 5.2.17 on 2026-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitychange',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups the changes of one bulk action for single-click undo.', null=True),
        ),
    ]
