# Generated by Django 5.2.17 on 2026-08-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('collection', '0002_quantitychange_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitychange',
            name='old_keeper_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Keeper reservation before the change, so undo can restore a reservation that was clamped away by a quantity drop.'),
        ),
        migrations.AddField(
            model_name='sellpackage',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sell_packages', to='catalog.game'),
        ),
    ]
