# Generated by Django 5.2.17 on 2026-08-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('archetype', models.CharField(blank=True, db_index=True, max_length=100)),
                ('format', models.CharField(default='TCG', max_length=30)),
                ('tier', models.CharField(choices=[('meta', 'Meta'), ('rogue', 'Rogue'), ('casual', 'Casual')], default='casual', max_length=10)),
                ('source_type', models.CharField(choices=[('imported', 'Imported'), ('manual', 'Manual'), ('curated', 'Curated')], default='manual', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('is_built', models.BooleanField(default=False, help_text='Physically assembled — reserves its copies in matching.')),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('section', models.CharField(choices=[('main', 'Main'), ('extra', 'Extra'), ('side', 'Side'), ('egg', 'Egg')], default='main', max_length=5)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.cardpiece')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deck', 'piece', 'section'), name='uniq_deckcard_deck_piece_section')],
            },
        ),
    ]
