# Generated by Django 5.2.17 on 2026-08-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('source_text', models.TextField(blank=True, help_text='Raw paste, kept for audit.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WantListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_line', models.CharField(max_length=250)),
                ('requested_name', models.CharField(max_length=250)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('matched_name_normalized', models.CharField(blank=True, max_length=250)),
                ('match_method', models.CharField(choices=[('exact', 'Exact'), ('normalized', 'Normalized'), ('fuzzy_confirmed', 'Fuzzy Confirmed'), ('manual', 'Manual'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('want_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wantlists.wantlist')),
            ],
        ),
    ]
