# Generated by Django 5.2.17 on 2026-08-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cardmarket_segment', models.CharField(help_text="URL path piece on cardmarket.com, e.g. 'YuGiOh'", max_length=50)),
                ('sheets_spreadsheet_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('fully_scraped', models.BooleanField(default=False)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expansions', to='catalog.game')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CardPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=30)),
                ('konami_id', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('card_type', models.CharField(blank=True, max_length=60)),
                ('race', models.CharField(blank=True, max_length=60)),
                ('attribute', models.CharField(blank=True, max_length=60)),
                ('archetype', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ban_tcg', models.CharField(blank=True, max_length=20)),
                ('is_extra_deck', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('catalog_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('catalog_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ambiguous_normalized', models.BooleanField(default=False, help_text='Another piece shares this normalized name; never auto-resolve.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='catalog.game')),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('name_normalized', models.CharField(db_index=True, max_length=250)),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('auto_exact', 'Auto Exact'), ('auto_fuzzy', 'Auto Fuzzy'), ('manual', 'Manual'), ('no_match', 'No Match'), ('ignored', 'Ignored')], default='unresolved', max_length=12)),
                ('resolution_confidence', models.FloatField(blank=True, null=True)),
                ('current_price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price_trend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prices_updated_at', models.DateTimeField(blank=True, null=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', to='catalog.expansion')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printings', to='catalog.cardpiece')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CardPieceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_passcode', models.CharField(db_index=True, max_length=30)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.cardpiece')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('piece', 'alias_passcode'), name='uniq_alias_piece_passcode')],
            },
        ),
        migrations.AddConstraint(
            model_name='expansion',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='uniq_expansion_game_slug'),
        ),
        migrations.AddConstraint(
            model_name='cardpiece',
            constraint=models.UniqueConstraint(fields=('game', 'external_id'), name='uniq_piece_game_extid'),
        ),
        migrations.AddConstraint(
            model_name='printing',
            constraint=models.UniqueConstraint(fields=('expansion', 'slug'), name='uniq_printing_expansion_slug'),
        ),
    ]
