# Generated by Django 5.2.17 on 2026-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpiece',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='atk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='ban_ocg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='colour',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='defence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='evolution_cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='frame_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='image_cropped_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='image_small_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='play_cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpiece',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardpiece',
            name='attribute',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cardpiece',
            name='card_type',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='cardpiece',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cardpiece',
            name='race',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
