# Generated by Django 5.2.17 on 2026-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cardpiece_options_cardpiece_atk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='price_source',
            field=models.CharField(blank=True, choices=[('scrape', 'Cardmarket (scraped)'), ('catalog', 'Catalog API (per-card estimate)')], db_index=True, max_length=10),
        ),
    ]
