# Generated by Django 5.2.17 on 2026-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_backfill_price_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='catalog_config',
            field=models.JSONField(blank=True, default=dict, help_text='For the "custom" provider: {"url": "...", "params": {}, "results_path": "data", "fields": {"external_id": "id", "name": "name", "image_url": "images.large"}, "image_url_template": "https://cdn.example/{external_id}.jpg"}. Dotted field paths reach into nested objects.'),
        ),
        migrations.AddField(
            model_name='game',
            name='catalog_provider',
            field=models.CharField(blank=True, choices=[('', 'No card catalog'), ('ygoprodeck', 'YGOPRODeck (Yu-Gi-Oh!)'), ('digimoncard', 'digimoncard.io (Digimon)'), ('custom', 'Custom JSON API (configured below)')], help_text='Which API supplies card names, types and artwork for this game.', max_length=20),
        ),
    ]
